POST http://localhost:8181/events
Content-Type: application/json
Authorization: "346d7f75-4b20-4166-8577-e656cdf3caea"

{
  "events": [
    {
      "id": "",
      "createdAt": "2",
      "type": "2",
      "project": "2",
      "projectBaseDir": "/mnt/c/Users/jaros/GolandProjects/tts",
      "language": "golang",
      "target": "2",
      "branch": "",
      "timezone": "2",
      "params": "some text2"
    },
    {
      "id": "",
      "createdAt": "2",
      "type": "2",
      "project": "2",
      "projectBaseDir": "/mnt/c/Users/jaros/GolandProjects/tts",
      "language": "golang",
      "target": "2",
      "branch": "",
      "timezone": "2",
      "params": "some text2"
    }
  ]
}