# This workflow will build release artifacts for different platforms and create a github release

name: Release

on:
  push:
    tags: [ "*" ]

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: 1.21
          dest: bin
          prefix: cli
          targets: windows/386,windows/amd64,windows/arm,darwin/amd64,darwin/arm64,linux/386,linux/amd64,linux/arm,linux/arm64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true

      - name: Archive binaries
        run: make zip-artifacts

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref, '-rc') }}
          files: ./bin/*.zip
